#!/usr/bin/env node
/**
 * adaptors/stitch/adaptor.js
 *
 * Generates a React overlay JSX component via Google Stitch.
 *
 * Usage:  node adaptor.js "<description>" [--out <path>] [--device MOBILE|DESKTOP|TABLET]
 * Stdout: absolute path to generated .jsx file
 * Stderr: JSON error on failure
 * Exit:   0 on success, 1 on failure
 *
 * Credential resolution order:
 *   1. MONTAJ_STITCH_API_KEY env var
 *   2. STITCH_API_KEY env var
 *   3. ~/.montaj/credentials.json → "stitch" key
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { resolve, join, dirname, basename } from "path";
import { fileURLToPath } from "url";
import { homedir } from "os";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Credential resolution
// ---------------------------------------------------------------------------

function resolveApiKey() {
  // 1. ~/.montaj/credentials.json (primary — user-managed, never committed)
  const credsPath = join(homedir(), ".montaj", "credentials.json");
  if (existsSync(credsPath)) {
    try {
      const creds = JSON.parse(readFileSync(credsPath, "utf8"));
      if (creds.stitch) return creds.stitch;
    } catch {}
  }

  // 2. Env vars (fallback — CI/CD or shell override)
  return process.env.MONTAJ_STITCH_API_KEY || process.env.STITCH_API_KEY || null;
}

// ---------------------------------------------------------------------------
// HTML → JSX
// ---------------------------------------------------------------------------

function htmlToJsx(html, description) {
  // Extract all <style> block contents
  const styleMatches = [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)];
  const css = styleMatches.map(m => m[1].trim()).join("\n");

  // Extract <body> content; fall back to stripping <head> if no body tag
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  const bodyHtml = bodyMatch
    ? bodyMatch[1].trim()
    : html
        .replace(/<head[\s\S]*?<\/head>/i, "")
        .replace(/<\/?html[^>]*>/gi, "")
        .replace(/<\/?body[^>]*>/gi, "")
        .trim();

  // Escape template-literal special characters for safe embedding
  const escape = s => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  const safeDesc = description.replace(/"/g, '\\"');

  return `// Generated by montaj adaptor stitch
// Description: "${safeDesc}"
// Render engine: transparent background, full 1080x1920 frame
export default function StitchOverlay({ frame, fps, duration, width, height }) {
  return (
    <>
      <style>{\`${escape(css)}\`}</style>
      <div
        style={{ position: "absolute", inset: 0, overflow: "hidden" }}
        dangerouslySetInnerHTML={{ __html: \`${escape(bodyHtml)}\` }}
      />
    </>
  );
}
`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fail(code, message) {
  process.stderr.write(JSON.stringify({ error: code, message }) + "\n");
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const argv = process.argv.slice(2);
  if (!argv.length || argv[0] === "--help") {
    process.stderr.write("Usage: adaptor.js <description> [--out <path>] [--device MOBILE|DESKTOP|TABLET]\n");
    process.exit(1);
  }

  let description = null;
  let outArg      = null;
  let device      = "MOBILE";

  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--out")    { outArg = argv[++i];  continue; }
    if (argv[i] === "--device") { device = argv[++i];  continue; }
    if (!description) description = argv[i];
  }

  if (!description) fail("missing_argument", "No description provided");

  const apiKey = resolveApiKey();
  if (!apiKey) {
    fail(
      "credential_missing",
      "Stitch API key not found. Set MONTAJ_STITCH_API_KEY or add 'stitch' to ~/.montaj/credentials.json. " +
      "Get a key at stitch.withgoogle.com → Settings.",
    );
  }

  // Set before dynamic import so the SDK reads it at initialisation
  process.env.STITCH_API_KEY = apiKey;

  const projectDir = process.env.MONTAJ_PROJECT_DIR || process.cwd();
  const outputPath = outArg
    ? resolve(outArg)
    : join(projectDir, "overlays", `stitch-${Date.now()}.jsx`);

  mkdirSync(dirname(outputPath), { recursive: true });

  // Dynamic import after env var is set
  let stitchModule;
  try {
    stitchModule = await import("@google/stitch-sdk");
  } catch (err) {
    fail(
      "missing_dependency",
      `@google/stitch-sdk not installed. Run: npm install --prefix adaptors/stitch`,
    );
  }

  const { stitch } = stitchModule;

  let html;
  try {
    const project = await stitch.createProject("montaj");
    const screen  = await project.generate(description, { deviceType: device });
    const htmlUrl = await screen.getHtml();

    // getHtml() returns a download URL — fetch the actual HTML
    const res = await fetch(htmlUrl);
    if (!res.ok) {
      fail("fetch_error", `Failed to download HTML from Stitch (HTTP ${res.status})`);
    }
    html = await res.text();
  } catch (err) {
    const msg = err?.message || String(err);
    if (/api.?key|credential|unauthori[zs]ed|permission/i.test(msg)) {
      fail("credential_invalid", `Stitch API key rejected: ${msg}`);
    }
    fail("stitch_error", msg);
  }

  const jsx = htmlToJsx(html, description);
  writeFileSync(outputPath, jsx, "utf8");

  process.stdout.write(outputPath + "\n");
}

main().catch(err => {
  process.stderr.write(JSON.stringify({ error: "adaptor_error", message: err?.message || String(err) }) + "\n");
  process.exit(1);
});
